import './admin/abi/abiRoutes'
import './admin/contractInstance/contractInstanceRoutes'
import './admin/liveObjectVersion/liveObjectVersionRoutes'
import './deployment/deploymentRoutes'
import './live-object/liveObjectRoutes'
import './project/projectRoutes'
import './user/userRoutes'
export { app } from './express'