import './admin/abi/abiRoutes'
import './admin/contract-instance/contractInstanceRoutes'
import './admin/live-object-version/liveObjectVersionRoutes'
import './admin/pipeline/pipelineRoutes'
import './abi/abiRoutes'
import './call-version/callVersionRoutes'
import './contract-instance/contractInstanceRoutes'
import './contract-registration-job/contractRegistrationJobRoutes'
import './deployment/deploymentRoutes'
import './event-version/eventVersionRoutes'
import './live-object/liveObjectRoutes'
import './live-object-version/liveObjectVersionRoutes'
import './project/projectRoutes'
import './user/userRoutes'
export { app } from './express'
