apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-generator-{{CHAIN_ID}}
  labels:
    app: event-generator-{{CHAIN_ID}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-generator-{{CHAIN_ID}}
  template:
    metadata:
      labels:
        app: event-generator-{{CHAIN_ID}}
    spec:
      containers:
      - name: event-generator-{{CHAIN_ID}}
        image: {{IMAGE}}
        env:
        - name: NODE_ENV
          value: production
        - name: CHAIN_ID
          value: "{{CHAIN_ID}}"
        - name: JWT_SECRET
          value: {{JWT_SECRET}}
        - name: INDEXER_REDIS_HOST
          value: {{INDEXER_REDIS_HOST}}
        - name: INDEXER_REDIS_PORT
          value: "{{INDEXER_REDIS_PORT}}"
        - name: EVENT_GENERATORS_JWT
          value: {{EVENT_GENERATORS_JWT}}
        - name: EVENT_RELAY_HOSTNAME
          value: {{EVENT_RELAY_HOSTNAME}}
        - name: EVENT_RELAY_PORT
          value: "443"
        - name: PUBLISHER_ROLE_KEY
          value: {{PUBLISHER_ROLE_KEY}}
        - name: CORE_DB_NAME
          value: {{CORE_DB_NAME}}
        - name: CORE_DB_HOST
          value: {{CORE_DB_HOST}}
        - name: CORE_DB_PORT
          value: "{{CORE_DB_PORT}}"
        - name: CORE_DB_USERNAME
          value: {{CORE_DB_USERNAME}}
        - name: CORE_DB_PASSWORD
          value: {{CORE_DB_PASSWORD}}
        - name: CORE_DB_MAX_POOL_SIZE
          value: "100"
        - name: BUGSNAG_API_KEY
          value: {{BUGSNAG_API_KEY}}
        - name: FORCE_COLOR
          value: "1" 
        - name: EVENT_GEN_RESPONSE_TIMEOUT
          value: "60000"
        - name: CONNECT_TO_EVENT_RELAY
          value: "true"
        - name: SHARED_TABLES_DB_NAME
          value: {{SHARED_TABLES_DB_NAME}}
        - name: SHARED_TABLES_DB_HOST
          value: {{SHARED_TABLES_DB_HOST}}
        - name: SHARED_TABLES_DB_PORT
          value: "{{SHARED_TABLES_DB_PORT}}"
        - name: SHARED_TABLES_DB_USERNAME
          value: {{SHARED_TABLES_DB_USERNAME}}
        - name: SHARED_TABLES_DB_PASSWORD
          value: {{SHARED_TABLES_DB_PASSWORD}}
        - name: SHARED_TABLES_MAX_POOL_SIZE
          value: "10"
        - name: INDEXER_DB_NAME
          value: {{INDEXER_DB_NAME}}
        - name: INDEXER_DB_HOST
          value: {{INDEXER_DB_HOST}}
        - name: INDEXER_DB_PORT
          value: "{{INDEXER_DB_PORT}}"
        - name: INDEXER_DB_USERNAME
          value: {{INDEXER_DB_USERNAME}}
        - name: INDEXER_DB_PASSWORD
          value: {{INDEXER_DB_PASSWORD}}
        - name: ABI_REDIS_HOST
          value: {{ABI_REDIS_HOST}}
        - name: ABI_REDIS_PORT
          value: "{{ABI_REDIS_PORT}}"

