apiVersion: apps/v1
kind: Deployment
metadata:
  name: delayed-jobs
  labels:
    app: delayed-jobs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: delayed-jobs
  template:
    metadata:
      labels:
        app: delayed-jobs
    spec:
      containers:
      - name: delayed-jobs
        image: {{IMAGE}}
        env:
        - name: NODE_ENV
          value: production
        - name: JWT_SECRET
          value: {{JWT_SECRET}}
        - name: EVENT_GENERATORS_JWT
          value: {{EVENT_GENERATORS_JWT}}
        - name: SHARED_TABLES_DB_NAME
          value: {{SHARED_TABLES_DB_NAME}}
        - name: SHARED_TABLES_DB_HOST
          value: {{SHARED_TABLES_DB_HOST}}
        - name: SHARED_TABLES_DB_PORT
          value: "{{SHARED_TABLES_DB_PORT}}"
        - name: SHARED_TABLES_DB_USERNAME
          value: {{SHARED_TABLES_DB_USERNAME}}
        - name: SHARED_TABLES_DB_PASSWORD
          value: {{SHARED_TABLES_DB_PASSWORD}}
        - name: SHARED_TABLES_MAX_POOL_SIZE
          value: "20"
        - name: INDEXER_REDIS_HOST
          value: {{INDEXER_REDIS_HOST}}
        - name: INDEXER_REDIS_PORT
          value: "{{INDEXER_REDIS_PORT}}"
        - name: ABI_REDIS_HOST
          value: {{ABI_REDIS_HOST}}
        - name: ABI_REDIS_PORT
          value: "{{ABI_REDIS_PORT}}"
        - name: DENO_DEPLOY_TOKEN
          value: {{DENO_DEPLOY_TOKEN}}
        - name: CORE_DB_NAME
          value: {{CORE_DB_NAME}}
        - name: CORE_DB_HOST
          value: {{CORE_DB_HOST}}
        - name: CORE_DB_PORT
          value: "{{CORE_DB_PORT}}"
        - name: CORE_DB_USERNAME
          value: {{CORE_DB_USERNAME}}
        - name: CORE_DB_PASSWORD
          value: {{CORE_DB_PASSWORD}}
        - name: ETHERSCAN_API_KEY
          value: {{ETHERSCAN_API_KEY}}
        - name: GOERLISCAN_API_KEY
          value: {{GOERLISCAN_API_KEY}}
        - name: POLYGONSCAN_API_KEY
          value: {{POLYGONSCAN_API_KEY}}
        - name: MUMBAISCAN_API_KEY
          value: {{MUMBAISCAN_API_KEY}}
        - name: POLYGON_ALCHEMY_REST_URL
          value: {{POLYGON_ALCHEMY_REST_URL}}
        - name: MUMBAI_ALCHEMY_REST_URL
          value: {{MUMBAI_ALCHEMY_REST_URL}}
        - name: FLIP
          value: TAILS
        - name: FORCE_COLOR
          value: "1" 
        - name: BUGSNAG_API_KEY
          value: {{BUGSNAG_API_KEY}}
