apiVersion: apps/v1
kind: Deployment
metadata:
  name: delayed-jobs
  labels:
    app: delayed-jobs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: delayed-jobs
  template:
    metadata:
      labels:
        app: delayed-jobs
    spec:
      containers:
      - name: delayed-jobs
        image: {{IMAGE}}
        env:
        - name: NODE_ENV
          value: production
        - name: SHARED_TABLES_DB_NAME
          value: {{SHARED_TABLES_DB_NAME}}
        - name: SHARED_TABLES_DB_HOST
          value: {{SHARED_TABLES_DB_HOST}}
        - name: SHARED_TABLES_DB_PORT
          value: "{{SHARED_TABLES_DB_PORT}}"
        - name: SHARED_TABLES_DB_USERNAME
          value: {{SHARED_TABLES_DB_USERNAME}}
        - name: SHARED_TABLES_DB_PASSWORD
          value: {{SHARED_TABLES_DB_PASSWORD}}
        - name: SHARED_TABLES_MAX_POOL_SIZE
          value: "10"
        - name: INDEXER_REDIS_HOST
          value: {{INDEXER_REDIS_HOST}}
        - name: INDEXER_REDIS_PORT
          value: "{{INDEXER_REDIS_PORT}}"
        - name: ABI_REDIS_HOST
          value: {{ABI_REDIS_HOST}}
        - name: ABI_REDIS_PORT
          value: "{{ABI_REDIS_PORT}}"
        - name: ETHERSCAN_API_KEY
          value: FBMK654QI5CTIYA7G8M7T7XEBGNHJSV1VG
        - name: DENO_DEPLOY_TOKEN
          value: {{DENO_DEPLOY_TOKEN}}