import { ev, config, StringKeyMap } from '../../shared'
import uuid4 from 'uuid4'

const coreApiConfig: StringKeyMap = {
    ...config,

    // SocketCluster 
    SOCKETCLUSTER_PORT: Number(ev('LOG_RELAY_SOCKETCLUSTER_PORT', 6666)),
    SOCKETCLUSTER_WS_ENGINE: ev('LOG_RELAY_SOCKETCLUSTER_WS_ENGINE', 'ws'),
    SOCKETCLUSTER_SOCKET_CHANNEL_LIMIT: Number(ev('LOG_RELAY_SOCKETCLUSTER_SOCKET_CHANNEL_LIMIT', 1000)),
    SOCKETCLUSTER_LOG_LEVEL: Number(ev('LOG_RELAY_SOCKETCLUSTER_LOG_LEVEL', 2)),
    SOCKETCLUSTER_OPTIONS: ev('LOG_RELAY_SOCKETCLUSTER_OPTIONS'),

    // SCC
    SCC_INSTANCE_ID: uuid4(),
    SCC_STATE_SERVER_HOST: ev('LOG_RELAY_SCC_STATE_SERVER_HOST'),
    SCC_STATE_SERVER_PORT: ev('LOG_RELAY_SCC_STATE_SERVER_PORT'),
    SCC_MAPPING_ENGINE: ev('LOG_RELAY_SCC_MAPPING_ENGINE'),
    SCC_CLIENT_POOL_SIZE: ev('LOG_RELAY_SCC_CLIENT_POOL_SIZE'),
    SCC_AUTH_KEY: ev('LOG_RELAY_SCC_AUTH_KEY'),
    SCC_INSTANCE_IP: ev('LOG_RELAY_SCC_INSTANCE_IP'),
    SCC_INSTANCE_IP_FAMILY: ev('LOG_RELAY_SCC_INSTANCE_IP_FAMILY'),
    SCC_STATE_SERVER_CONNECT_TIMEOUT: Number(ev('LOG_RELAY_SCC_STATE_SERVER_CONNECT_TIMEOUT')),
    SCC_STATE_SERVER_ACK_TIMEOUT: Number(ev('LOG_RELAY_SCC_STATE_SERVER_ACK_TIMEOUT')),
    SCC_STATE_SERVER_RECONNECT_RANDOMNESS: Number(ev('LOG_RELAY_SCC_STATE_SERVER_RECONNECT_RANDOMNESS')),
    SCC_PUB_SUB_BATCH_DURATION: Number(ev('LOG_RELAY_SCC_PUB_SUB_BATCH_DURATION')),
    SCC_BROKER_RETRY_DELAY: Number(ev('LOG_RELAY_SCC_BROKER_RETRY_DELAY')),
}

export default coreApiConfig