apiVersion: apps/v1
kind: Deployment
metadata:
  name: functions
  labels:
    app: functions
spec:
  replicas: 3
  selector:
    matchLabels:
      app: functions
  template:
    metadata:
      labels:
        app: functions 
    spec:
      containers:
      - name: functions
        image: {{IMAGE}}
        ports:
        - containerPort: 80
        env:
        - name: NODE_ENV
          value: production
        - name: PORT
          value: "{{PORT}}"
---
apiVersion: v1
kind: Service
metadata:
  name: functions
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: {{ACM_WILDCARD_CERT_ARM}}
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
spec:
  selector:
    app: functions 
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: {{PORT}}
  - name: https
    port: 443
    targetPort: {{PORT}}