apiVersion: apps/v1
kind: Deployment
metadata:
  name: tables-api-new
  labels:
    app: tables-api-new
spec:
  replicas: 5
  selector:
    matchLabels:
      component: tables-api-new
  template:
    metadata:
      labels:
        component: tables-api-new
    spec:
      containers:
      - name: tables-api-new
        image: {{IMAGE}}
        ports:
        - name: tables-api-new
          containerPort: 80
        env:
        - name: NODE_ENV
          value: production
        - name: PORT
          value: "{{PORT}}"
        - name: STREAM_BATCH_SIZE
          value: "{{STREAM_BATCH_SIZE}}"
        - name: SHARED_TABLES_DB_NAME
          value: {{SHARED_TABLES_DB_NAME}}
        - name: SHARED_TABLES_DB_HOST
          value: {{SHARED_TABLES_DB_HOST}}
        - name: SHARED_TABLES_DB_PORT
          value: "{{SHARED_TABLES_DB_PORT}}"
        - name: SHARED_TABLES_DB_USERNAME
          value: {{SHARED_TABLES_DB_USERNAME}}
        - name: SHARED_TABLES_DB_PASSWORD
          value: {{SHARED_TABLES_DB_PASSWORD}}
        - name: SHARED_TABLES_DEFAULT_ROLE
          value: {{SHARED_TABLES_DEFAULT_ROLE}}
        - name: SHARED_TABLES_MAX_POOL_SIZE
          value: "100"
        - name: BUGSNAG_API_KEY
          value: {{BUGSNAG_API_KEY}}
        - name: JWT_SECRET
          value: {{JWT_SECRET}}
        - name: FLIP
          value: tails
        readinessProbe:
          httpGet:
            path: /health-check
            port: tables-api-new
          initialDelaySeconds: 5
          timeoutSeconds: 10
        livenessProbe:
          httpGet:
            path: /health-check
            port: tables-api-new
          initialDelaySeconds: 15
          timeoutSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: tables-api-new
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
  selector:
    component: tables-api-new
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tables-api-new
  annotations:
    kubernetes.io/ingress.class: "tables-nginx"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: tables-api-new
            port:
              number: 80