apiVersion: apps/v1
kind: Deployment
metadata:
  name: tables-api
  labels:
    app: tables-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tables-api
  template:
    metadata:
      labels:
        app: tables-api 
    spec:
      containers:
      - name: tables-api
        image: {{IMAGE}}
        ports:
        - containerPort: 80
        env:
        - name: NODE_ENV
          value: production
        - name: PORT
          value: "{{PORT}}"
        - name: STREAM_BATCH_SIZE
          value: "{{STREAM_BATCH_SIZE}}"
        - name: SHARED_TABLES_DB_NAME
          value: {{SHARED_TABLES_DB_NAME}}
        - name: SHARED_TABLES_DB_HOST
          value: {{SHARED_TABLES_DB_HOST}}
        - name: SHARED_TABLES_DB_PORT
          value: "{{SHARED_TABLES_DB_PORT}}"
        - name: SHARED_TABLES_DB_USERNAME
          value: {{SHARED_TABLES_DB_USERNAME}}
        - name: SHARED_TABLES_DB_PASSWORD
          value: {{SHARED_TABLES_DB_PASSWORD}}
        - name: SHARED_TABLES_MAX_POOL_SIZE
          value: "100"
        - name: FLIP
          value: heads
---
apiVersion: v1
kind: Service
metadata:
  name: tables-api
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: {{ACM_WILDCARD_CERT_ARM}}
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
spec:
  selector:
    app: tables-api 
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: {{PORT}}
  - name: https
    port: 443
    targetPort: {{PORT}}