apiVersion: apps/v1
kind: Deployment
metadata:
  name: tables-api-primary
  labels:
    app: tables-api-primary
spec:
  replicas: 4
  selector:
    matchLabels:
      component: tables-api-primary
  template:
    metadata:
      labels:
        component: tables-api-primary
    spec:
      containers:
      - name: tables-api-primary
        image: {{IMAGE}}
        ports:
        - name: tables-api-pr
          containerPort: 80
        env:
        - name: NODE_ENV
          value: production
        - name: PORT
          value: "{{PORT}}"
        - name: STREAM_BATCH_SIZE
          value: "{{STREAM_BATCH_SIZE}}"
        - name: SHARED_TABLES_DB_NAME
          value: {{SHARED_TABLES_DB_NAME}}
        - name: SHARED_TABLES_DB_HOST
          value: {{SHARED_TABLES_DB_HOST}}
        - name: SHARED_TABLES_DB_PORT
          value: "{{SHARED_TABLES_DB_PORT}}"
        - name: SHARED_TABLES_DB_USERNAME
          value: {{SHARED_TABLES_DB_USERNAME}}
        - name: SHARED_TABLES_DB_PASSWORD
          value: {{SHARED_TABLES_DB_PASSWORD}}
        - name: SHARED_TABLES_DEFAULT_ROLE
          value: {{SHARED_TABLES_DEFAULT_ROLE}}
        - name: SHARED_TABLES_READER_HOST
          value: {{SHARED_TABLES_READER_HOST}}
        - name: SHARED_TABLES_READER_USERNAME
          value: {{SHARED_TABLES_READER_USERNAME}}
        - name: SHARED_TABLES_READER_PASSWORD
          value: {{SHARED_TABLES_READER_PASSWORD}}
        - name: SHARED_TABLES_MAX_POOL_SIZE
          value: "100"
        - name: SHARED_TABLES_DB_URL
          value: {{SHARED_TABLES_DB_URL}}
        - name: ETHEREUM_DB_URL
          value: {{ETHEREUM_DB_URL}}
        - name: GOERLI_DB_URL
          value: {{GOERLI_DB_URL}}
        - name: POLYGON_DB_URL
          value: {{POLYGON_DB_URL}}
        - name: MUMBAI_DB_URL
          value: {{MUMBAI_DB_URL}}
        - name: BASE_DB_URL
          value: {{BASE_DB_URL}}
        - name: INDEXER_REDIS_HOST
          value: {{INDEXER_REDIS_HOST}}
        - name: INDEXER_REDIS_PORT
          value: "{{INDEXER_REDIS_PORT}}"
        - name: BUGSNAG_API_KEY
          value: {{BUGSNAG_API_KEY}}
        - name: JWT_SECRET
          value: {{JWT_SECRET}}
        - name: FLIP
          value: tails
        - name: FORCE_COLOR
          value: "1" 
        readinessProbe:
          httpGet:
            path: /health-check
            port: tables-api-pr
          initialDelaySeconds: 5
          timeoutSeconds: 10
        livenessProbe:
          httpGet:
            path: /health-check
            port: tables-api-pr
          initialDelaySeconds: 15
          timeoutSeconds: 20
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tables-api-reader
  labels:
    app: tables-api-reader
spec:
  replicas: 6
  selector:
    matchLabels:
      component: tables-api-reader
  template:
    metadata:
      labels:
        component: tables-api-reader
    spec:
      containers:
      - name: tables-api-reader
        image: {{IMAGE}}
        ports:
        - name: tables-api-rr
          containerPort: 80
        env:
        - name: IS_READ_ONLY
          value: "true"
        - name: NODE_ENV
          value: production
        - name: PORT
          value: "{{PORT}}"
        - name: STREAM_BATCH_SIZE
          value: "{{STREAM_BATCH_SIZE}}"
        - name: SHARED_TABLES_DB_NAME
          value: {{SHARED_TABLES_DB_NAME}}
        - name: SHARED_TABLES_DB_HOST
          value: {{SHARED_TABLES_DB_HOST}}
        - name: SHARED_TABLES_DB_PORT
          value: "{{SHARED_TABLES_DB_PORT}}"
        - name: SHARED_TABLES_DB_USERNAME
          value: {{SHARED_TABLES_DB_USERNAME}}
        - name: SHARED_TABLES_DB_PASSWORD
          value: {{SHARED_TABLES_DB_PASSWORD}}
        - name: SHARED_TABLES_DEFAULT_ROLE
          value: {{SHARED_TABLES_DEFAULT_ROLE}}
        - name: SHARED_TABLES_READER_HOST
          value: {{SHARED_TABLES_READER_HOST}}
        - name: SHARED_TABLES_READER_USERNAME
          value: {{SHARED_TABLES_READER_USERNAME}}
        - name: SHARED_TABLES_READER_PASSWORD
          value: {{SHARED_TABLES_READER_PASSWORD}}
        - name: SHARED_TABLES_MAX_POOL_SIZE
          value: "100"
        - name: SHARED_TABLES_DB_URL
          value: {{SHARED_TABLES_DB_URL}}
        - name: ETHEREUM_DB_URL
          value: {{ETHEREUM_DB_URL}}
        - name: GOERLI_DB_URL
          value: {{GOERLI_DB_URL}}
        - name: POLYGON_DB_URL
          value: {{POLYGON_DB_URL}}
        - name: MUMBAI_DB_URL
          value: {{MUMBAI_DB_URL}}
        - name: BASE_DB_URL
          value: {{BASE_DB_URL}}
        - name: BUGSNAG_API_KEY
          value: {{BUGSNAG_API_KEY}}
        - name: JWT_SECRET
          value: {{JWT_SECRET}}
        - name: INDEXER_REDIS_HOST
          value: {{INDEXER_REDIS_HOST}}
        - name: INDEXER_REDIS_PORT
          value: "{{INDEXER_REDIS_PORT}}"
        - name: FLIP
          value: heads
        - name: FORCE_COLOR
          value: "1" 
        readinessProbe:
          httpGet:
            path: /health-check
            port: tables-api-rr
          initialDelaySeconds: 5
          timeoutSeconds: 10
        livenessProbe:
          httpGet:
            path: /health-check
            port: tables-api-rr
          initialDelaySeconds: 15
          timeoutSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: tables-api-primary
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
  selector:
    component: tables-api-primary
---
apiVersion: v1
kind: Service
metadata:
  name: tables-api-reader
spec:
  type: NodePort
  ports:
  - port: 81
    targetPort: 80
  selector:
    component: tables-api-reader
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tables-api-ingress
  annotations:
    kubernetes.io/ingress.class: "tables-api-nginx"
spec:
  rules:
  - http:
      paths:
      - path: /stream
        pathType: Prefix
        backend:
          service:
            name: tables-api-reader
            port:
              number: 81
      - path: /
        pathType: Prefix
        backend:
          service:
            name: tables-api-primary
            port:
              number: 80