apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{JOB_NAME}}
spec:
  schedule: {{JOB_SCHEDULE}}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{JOB_NAME}}
            image: {{IMAGE}}
            env:
            - name: NODE_ENV
              value: production
            - name: JOB_NAME
              value: {{JOB_NAME}}
            - name: CMC_API_KEY
              value: {{CMC_API_KEY}}
            - name: CORE_REDIS_HOST
              value: {{CORE_REDIS_HOST}}
            - name: CORE_REDIS_PORT
              value: "{{CORE_REDIS_PORT}}"
            - name: SHARED_TABLES_DB_NAME
              value: {{SHARED_TABLES_DB_NAME}}
            - name: SHARED_TABLES_DB_HOST
              value: {{SHARED_TABLES_DB_HOST}}
            - name: SHARED_TABLES_DB_PORT
              value: "{{SHARED_TABLES_DB_PORT}}"
            - name: SHARED_TABLES_DB_USERNAME
              value: {{SHARED_TABLES_DB_USERNAME}}
            - name: SHARED_TABLES_DB_PASSWORD
              value: {{SHARED_TABLES_DB_PASSWORD}}
            - name: SHARED_TABLES_MAX_POOL_SIZE
              value: "20"
          restartPolicy: OnFailure