apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{DEPLOYMENT_NAME}}
  labels:
    app: {{DEPLOYMENT_NAME}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{DEPLOYMENT_NAME}}
  template:
    metadata:
      labels:
        app: {{DEPLOYMENT_NAME}} 
    spec:
      containers:
      - name: {{DEPLOYMENT_NAME}}
        image: {{IMAGE}}
        env:
        - name: NODE_ENV
          value: production
        - name: JOB_NAME
          value: {{JOB_NAME}}
        - name: CMC_API_KEY
          value: {{CMC_API_KEY}}
        - name: CORE_REDIS_HOST
          value: {{CORE_REDIS_HOST}}
        - name: CORE_REDIS_PORT
          value: "{{CORE_REDIS_PORT}}"
        - name: SHARED_TABLES_DB_NAME
          value: {{SHARED_TABLES_DB_NAME}}
        - name: SHARED_TABLES_DB_HOST
          value: {{SHARED_TABLES_DB_HOST}}
        - name: SHARED_TABLES_DB_PORT
          value: "{{SHARED_TABLES_DB_PORT}}"
        - name: SHARED_TABLES_DB_USERNAME
          value: {{SHARED_TABLES_DB_USERNAME}}
        - name: SHARED_TABLES_DB_PASSWORD
          value: {{SHARED_TABLES_DB_PASSWORD}}
        - name: SHARED_TABLES_DB_URL
          value: {{SHARED_TABLES_DB_URL}}
        - name: SHARED_TABLES_MIN_POOL_SIZE
          value: "0"
        - name: SHARED_TABLES_MAX_POOL_SIZE
          value: "20"
        - name: CORE_DB_NAME
          value: {{CORE_DB_NAME}}
        - name: CORE_DB_HOST
          value: {{CORE_DB_HOST}}
        - name: CORE_DB_PORT
          value: "{{CORE_DB_PORT}}"
        - name: CORE_DB_USERNAME
          value: {{CORE_DB_USERNAME}}
        - name: CORE_DB_PASSWORD
          value: {{CORE_DB_PASSWORD}}
        - name: ALGOLIA_APPLICATION_ID
          value: {{ALGOLIA_APPLICATION_ID}}
        - name: ALGOLIA_ADMIN_API_KEY
          value: {{ALGOLIA_ADMIN_API_KEY}}
        - name: ALGOLIA_SYNC_ALL
          value: "false"
        - name: ETHEREUM_DB_URL
          value: {{ETHEREUM_DB_URL}}
        - name: GOERLI_DB_URL
          value: {{GOERLI_DB_URL}}
        - name: POLYGON_DB_URL
          value: {{POLYGON_DB_URL}}
        - name: MUMBAI_DB_URL
          value: {{MUMBAI_DB_URL}}
        - name: BASE_DB_URL
          value: {{BASE_DB_URL}}
        - name: OPTIMISM_DB_URL
          value: {{OPTIMISM_DB_URL}}
        - name: ARBITRUM_DB_URL
          value: {{ARBITRUM_DB_URL}}
        - name: ARBITRUM_SEPOLIA_DB_URL
          value: {{ARBITRUM_SEPOLIA_DB_URL}}
        - name: PGN_DB_URL
          value: {{PGN_DB_URL}}
        - name: CELO_DB_URL
          value: {{CELO_DB_URL}}
        - name: LINEA_DB_URL
          value: {{LINEA_DB_URL}}
        - name: SEPOLIA_DB_URL
          value: {{SEPOLIA_DB_URL}}
        - name: FORCE_COLOR
          value: "1" 
        - name: JOB_INTERVAL
          value: "60000"
        - name: FLIP
          value: tails