apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-sorter-{{CHAIN_ID}}
  labels:
    app: event-sorter-{{CHAIN_ID}}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: event-sorter-{{CHAIN_ID}}
  template:
    metadata:
      labels:
        app: event-sorter-{{CHAIN_ID}}
    spec:
      containers:
      - name: event-sorter-{{CHAIN_ID}}
        image: {{IMAGE}}
        env:
        - name: NODE_ENV
          value: production
        - name: CHAIN_ID
          value: "{{CHAIN_ID}}"
