apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-sorter-{{CHAIN_ID}}
  labels:
    app: event-sorter-{{CHAIN_ID}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-sorter-{{CHAIN_ID}}
  template:
    metadata:
      labels:
        app: event-sorter-{{CHAIN_ID}}
    spec:
      containers:
      - name: event-sorter-{{CHAIN_ID}}
        image: {{IMAGE}}
        env:
        - name: NODE_ENV
          value: production
        - name: CHAIN_ID
          value: "{{CHAIN_ID}}"
        - name: INDEXER_REDIS_HOST
          value: {{INDEXER_REDIS_HOST}}
        - name: INDEXER_REDIS_PORT
          value: "{{INDEXER_REDIS_PORT}}"
        - name: BUGSNAG_API_KEY
          value: {{BUGSNAG_API_KEY}}
        - name: FORCE_COLOR
          value: "1" 
        - name: WARN_AT_GAP_SIZE
          value: "50"