apiVersion: apps/v1
kind: Deployment
metadata:
  name: head-reporter-{{CHAIN_ID}}
  labels:
    app: head-reporter-{{CHAIN_ID}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: head-reporter-{{CHAIN_ID}}
  template:
    metadata:
      labels:
        app: head-reporter-{{CHAIN_ID}} 
    spec:
      containers:
      - name: head-reporter-{{CHAIN_ID}}
        image: {{IMAGE}}
        env:
        - name: NODE_ENV
          value: production
        - name: CHAIN_ID
          value: "{{CHAIN_ID}}"
        - name: ALCHEMY_API_KEY
          value: {{ALCHEMY_API_KEY}}
        - name: ALCHEMY_SUBSCRIPTION_URL
          value: {{ALCHEMY_SUBSCRIPTION_URL}}
        - name: HEAD_REPORTER_QUEUE_KEY
          value: {{HEAD_REPORTER_QUEUE_KEY}}
        - name: INDEXER_REDIS_HOST
          value: {{INDEXER_REDIS_HOST}}
        - name: INDEXER_REDIS_PORT
          value: "{{INDEXER_REDIS_PORT}}"
        - name: INDEXER_DB_NAME
          value: {{INDEXER_DB_NAME}}
        - name: INDEXER_DB_HOST
          value: {{INDEXER_DB_HOST}}
        - name: INDEXER_DB_PORT
          value: "{{INDEXER_DB_PORT}}"
        - name: INDEXER_DB_USERNAME
          value: {{INDEXER_DB_USERNAME}}
        - name: INDEXER_DB_PASSWORD
          value: {{INDEXER_DB_PASSWORD}}
        - name: HEAD_BUFFER
          value: "{{HEAD_BUFFER}}"
        - name: SHARED_TABLES_DB_NAME
          value: {{SHARED_TABLES_DB_NAME}}
        - name: SHARED_TABLES_DB_HOST
          value: {{SHARED_TABLES_DB_HOST}}
        - name: SHARED_TABLES_DB_PORT
          value: "{{SHARED_TABLES_DB_PORT}}"
        - name: SHARED_TABLES_DB_USERNAME
          value: {{SHARED_TABLES_DB_USERNAME}}
        - name: SHARED_TABLES_DB_PASSWORD
          value: {{SHARED_TABLES_DB_PASSWORD}}
        - name: SHARED_TABLES_MAX_POOL_SIZE
          value: "100"

