apiVersion: batch/v1
kind: Job
metadata:
  name: {{JOB_NAME}}
  labels:
    type: manual-reporter
spec:
  template:
    metadata:
      labels:
        type: manual-reporter
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            type: manual-reporter
      containers:
      - name: manual-reporter
        image: {{IMAGE}}
        env:
        - name: NODE_ENV
          value: production
        - name: MANUALLY_REPORT_NUMBERS
          value: "{{MANUALLY_REPORT_NUMBERS}}"
        - name: FORCE_REINDEX
          value: "{{FORCE_REINDEX}}"
        - name: CHAIN_ID
          value: "{{CHAIN_ID}}"
        - name: ALCHEMY_API_KEY
          value: {{ALCHEMY_API_KEY}}
        - name: ALCHEMY_SUBSCRIPTION_URL
          value: {{ALCHEMY_SUBSCRIPTION_URL}}
        - name: HEAD_REPORTER_QUEUE_KEY
          value: {{HEAD_REPORTER_QUEUE_KEY}}
        - name: INDEXER_REDIS_HOST
          value: {{INDEXER_REDIS_HOST}}
        - name: INDEXER_REDIS_PORT
          value: "{{INDEXER_REDIS_PORT}}"
        - name: INDEXER_DB_NAME
          value: {{INDEXER_DB_NAME}}
        - name: INDEXER_DB_HOST
          value: {{INDEXER_DB_HOST}}
        - name: INDEXER_DB_PORT
          value: "{{INDEXER_DB_PORT}}"
        - name: INDEXER_DB_USERNAME
          value: {{INDEXER_DB_USERNAME}}
        - name: INDEXER_DB_PASSWORD
          value: {{INDEXER_DB_PASSWORD}}
      restartPolicy: Never