apiVersion: batch/v1
kind: Job
metadata:
  name: {{JOB_NAME}}
  labels:
    type: rollback-table-job
spec:
  template:
    metadata:
      labels:
        type: rollback-table-job
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            type: rollback-table-job
      containers:
      - name: rollback-table-job
        image: {{IMAGE}}
        env:
        - name: NODE_ENV
          value: production
        - name: ROLLBACK_TABLE
          value: "{{ROLLBACK_TABLE}}"
        - name: ROLLBACK_TARGET
          value: "{{ROLLBACK_TARGET}}"
        - name: CHAIN_ID
          value: "{{CHAIN_ID}}"
        - name: WS_PROVIDER_POOL
          value: {{WS_PROVIDER_POOL}}
        - name: INDEXER_REDIS_HOST
          value: {{INDEXER_REDIS_HOST}}
        - name: INDEXER_REDIS_PORT
          value: "{{INDEXER_REDIS_PORT}}"
        - name: INDEXER_DB_NAME
          value: {{INDEXER_DB_NAME}}
        - name: INDEXER_DB_HOST
          value: {{INDEXER_DB_HOST}}
        - name: INDEXER_DB_PORT
          value: "{{INDEXER_DB_PORT}}"
        - name: INDEXER_DB_USERNAME
          value: {{INDEXER_DB_USERNAME}}
        - name: INDEXER_DB_PASSWORD
          value: {{INDEXER_DB_PASSWORD}}
        - name: SHARED_TABLES_DB_NAME
          value: {{SHARED_TABLES_DB_NAME}}
        - name: SHARED_TABLES_DB_HOST
          value: {{SHARED_TABLES_DB_HOST}}
        - name: SHARED_TABLES_DB_PORT
          value: "{{SHARED_TABLES_DB_PORT}}"
        - name: SHARED_TABLES_DB_USERNAME
          value: {{SHARED_TABLES_DB_USERNAME}}
        - name: SHARED_TABLES_DB_PASSWORD
          value: {{SHARED_TABLES_DB_PASSWORD}}
        - name: SHARED_TABLES_MAX_POOL_SIZE
          value: "10"
        - name: SHARED_TABLES_OPTIONS
          value: "-c statement_timeout=120000ms"
        - name: CORE_DB_NAME
          value: {{CORE_DB_NAME}}
        - name: CORE_DB_HOST
          value: {{CORE_DB_HOST}}
        - name: CORE_DB_PORT
          value: "{{CORE_DB_PORT}}"
        - name: CORE_DB_USERNAME
          value: {{CORE_DB_USERNAME}}
        - name: CORE_DB_PASSWORD
          value: {{CORE_DB_PASSWORD}}
      restartPolicy: Never