apiVersion: batch/v1
kind: Job
metadata:
  name: {{JOB_NAME}}
  labels:
    type: live-object-indexer
spec:
  template:
    metadata:
      labels:
        type: live-object-indexer
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            type: live-object-indexer
      containers:
      - name: live-object-indexer
        image: {{IMAGE}}
        env:
        - name: NODE_ENV
          value: production
        - name: JWT_SECRET
          value: {{JWT_SECRET}}
        - name: EVENT_GENERATORS_JWT
          value: {{EVENT_GENERATORS_JWT}}
        - name: LIVE_OBJECT_VERSION_ID
          value: "{{LIVE_OBJECT_VERSION_ID}}"
        - name: CORE_DB_NAME
          value: {{CORE_DB_NAME}}
        - name: CORE_DB_HOST
          value: {{CORE_DB_HOST}}
        - name: CORE_DB_PORT
          value: "{{CORE_DB_PORT}}"
        - name: CORE_DB_USERNAME
          value: {{CORE_DB_USERNAME}}
        - name: CORE_DB_PASSWORD
          value: {{CORE_DB_PASSWORD}}
        - name: SHARED_TABLES_DB_NAME
          value: {{SHARED_TABLES_DB_NAME}}
        - name: SHARED_TABLES_DB_HOST
          value: {{SHARED_TABLES_DB_HOST}}
        - name: SHARED_TABLES_DB_PORT
          value: "{{SHARED_TABLES_DB_PORT}}"
        - name: SHARED_TABLES_DB_USERNAME
          value: {{SHARED_TABLES_DB_USERNAME}}
        - name: SHARED_TABLES_DB_PASSWORD
          value: {{SHARED_TABLES_DB_PASSWORD}}
        - name: SHARED_TABLES_MAX_POOL_SIZE
          value: "100"
        - name: BUGSNAG_API_KEY
          value: {{BUGSNAG_API_KEY}}
        - name: START_BLOCK_NUMBER
          value: "39528000"
      restartPolicy: Never