apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-relay
spec:
  replicas: 1
  selector:
    matchLabels:
      component: event-relay
  template:
    metadata:
      labels:
        component: event-relay
    spec:
      containers:
      - name: event-relay
        image: {{IMAGE}}
        ports:
        - name: event-relay
          containerPort: {{SOCKETCLUSTER_PORT}}
        env:
        - name: SCC_INSTANCE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: ENV
          value: prod
        - name: JWT_SECRET
          value: {{JWT_SECRET}}
        - name: SOCKETCLUSTER_PORT
          value: "{{SOCKETCLUSTER_PORT}}"
        - name: SOCKETCLUSTER_LOG_LEVEL
          value: "{{SOCKETCLUSTER_LOG_LEVEL}}"
        - name: CORE_DB_NAME
          value: {{CORE_DB_NAME}}
        - name: CORE_DB_HOST
          value: {{CORE_DB_HOST}}
        - name: CORE_DB_PORT
          value: "{{CORE_DB_PORT}}"
        - name: CORE_DB_USERNAME
          value: {{CORE_DB_USERNAME}}
        - name: CORE_DB_PASSWORD
          value: {{CORE_DB_PASSWORD}}
        readinessProbe:
          httpGet:
            path: /health-check
            port: event-relay
          initialDelaySeconds: 5
          timeoutSeconds: 10
        livenessProbe:
          httpGet:
            path: /health-check
            port: event-relay
          initialDelaySeconds: 15
          timeoutSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: event-relay
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: {{SOCKETCLUSTER_PORT}}
  selector:
    component: event-relay
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: event-relay
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: event-relay
            port:
              number: 80