apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-relay-scc-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      component: event-relay-scc-broker
  template:
    metadata:
      labels:
        component: event-relay-scc-broker
    spec:
      containers:
      - name: event-relay-scc-broker
        image: socketcluster/scc-broker:v8.0.0
        ports:
        - name: er-scc-broker
          containerPort: {{SCC_BROKER_PORT}}
        env:
        - name: SCC_STATE_SERVER_HOST
          value: event-relay-scc-state
        - name: SCC_INSTANCE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: SCC_BROKER_SERVER_LOG_LEVEL
          value: "2"
        readinessProbe:
          httpGet:
            path: /health-check
            port: er-scc-broker
          initialDelaySeconds: 5
          timeoutSeconds: 10
        livenessProbe:
          httpGet:
            path: /health-check
            port: er-scc-broker
          initialDelaySeconds: 15
          timeoutSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: event-relay-scc-broker
spec:
  type: ClusterIP
  ports:
  - port: {{SCC_BROKER_PORT}}
    targetPort: {{SCC_BROKER_PORT}}
  selector:
    component: event-relay-scc-broker
