apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-relay-scc-state
spec:
  replicas: 1
  selector:
    matchLabels:
      component: event-relay-scc-state
  template:
    metadata:
      labels:
        component: event-relay-scc-state
    spec:
      containers:
      - name: event-relay-scc-state
        image: socketcluster/scc-state:v8.0.2
        ports:
        - name: er-scc-state
          containerPort: {{SCC_STATE_SERVER_PORT}}
        readinessProbe:
          httpGet:
            path: /health-check
            port: er-scc-state
          initialDelaySeconds: 5
          timeoutSeconds: 10
        livenessProbe:
          httpGet:
            path: /health-check
            port: er-scc-state
          initialDelaySeconds: 15
          timeoutSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: event-relay-scc-state
spec:
  type: ClusterIP
  ports:
  - port: {{SCC_STATE_SERVER_PORT}}
    targetPort: {{SCC_STATE_SERVER_PORT}}
  selector:
    component: event-relay-scc-state