CREATE OR REPLACE VIEW goerli.txs AS
SELECT
    hash,
    nonce,
    transaction_index,
    "from",
    "to",
    contract_address,
    value,
    input,
    function_name,
    function_args,
    transaction_type,
    status,
    root,
    gas,
    gas_price,
    max_fee_per_gas,
    max_priority_fee_per_gas,
    gas_used,
    cumulative_gas_used,
    effective_gas_price,
    block_hash,
    block_number,
    block_timestamp,
    unnest(ARRAY['5'::text]) AS chain_id
FROM goerli.transactions;

CREATE OR REPLACE VIEW ethereum.txs AS
SELECT
    hash,
    nonce,
    transaction_index,
    "from",
    "to",
    contract_address,
    value,
    input,
    function_name,
    function_args,
    transaction_type,
    status,
    root,
    gas,
    gas_price,
    max_fee_per_gas,
    max_priority_fee_per_gas,
    gas_used,
    cumulative_gas_used,
    effective_gas_price,
    block_hash,
    block_number,
    block_timestamp,
    unnest(ARRAY['1'::text]) AS chain_id
FROM ethereum.transactions;

CREATE OR REPLACE VIEW polygon.txs AS
SELECT
    hash,
    nonce,
    transaction_index,
    "from",
    "to",
    contract_address,
    value,
    input,
    function_name,
    function_args,
    transaction_type,
    status,
    root,
    gas,
    gas_price,
    max_fee_per_gas,
    max_priority_fee_per_gas,
    gas_used,
    cumulative_gas_used,
    effective_gas_price,
    block_hash,
    block_number,
    block_timestamp,
    unnest(ARRAY['137'::text]) AS chain_id
FROM polygon.transactions;