apiVersion: v1
kind: Service
metadata:
  name: event-relay-scc-state
spec:
  type: ClusterIP
  ports:
  - port: {{SCC_STATE_SERVER_PORT}}
    targetPort: {{SCC_STATE_SERVER_PORT}}
  selector:
    component: event-relay-scc-state