apiVersion: v1
kind: Service
metadata:
  name: event-relay-scc-broker
spec:
  type: ClusterIP
  ports:
  - port: {{SCC_BROKER_PORT}}
    targetPort: {{SCC_BROKER_PORT}}
  selector:
    component: event-relay-scc-broker
